// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protofiles/payment_gateway.proto

package protofiles

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetBalanceRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalanceRequest) Reset()         { *m = GetBalanceRequest{} }
func (m *GetBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*GetBalanceRequest) ProtoMessage()    {}
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60b917c2932c744, []int{0}
}

func (m *GetBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceRequest.Unmarshal(m, b)
}
func (m *GetBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceRequest.Marshal(b, m, deterministic)
}
func (m *GetBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceRequest.Merge(m, src)
}
func (m *GetBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_GetBalanceRequest.Size(m)
}
func (m *GetBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceRequest proto.InternalMessageInfo

func (m *GetBalanceRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetBalanceResponse struct {
	Amount               float32  `protobuf:"fixed32,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalanceResponse) Reset()         { *m = GetBalanceResponse{} }
func (m *GetBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*GetBalanceResponse) ProtoMessage()    {}
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60b917c2932c744, []int{1}
}

func (m *GetBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceResponse.Unmarshal(m, b)
}
func (m *GetBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceResponse.Marshal(b, m, deterministic)
}
func (m *GetBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceResponse.Merge(m, src)
}
func (m *GetBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_GetBalanceResponse.Size(m)
}
func (m *GetBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceResponse proto.InternalMessageInfo

func (m *GetBalanceResponse) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type UserCredentials struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCredentials) Reset()         { *m = UserCredentials{} }
func (m *UserCredentials) String() string { return proto.CompactTextString(m) }
func (*UserCredentials) ProtoMessage()    {}
func (*UserCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60b917c2932c744, []int{2}
}

func (m *UserCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCredentials.Unmarshal(m, b)
}
func (m *UserCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCredentials.Marshal(b, m, deterministic)
}
func (m *UserCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCredentials.Merge(m, src)
}
func (m *UserCredentials) XXX_Size() int {
	return xxx_messageInfo_UserCredentials.Size(m)
}
func (m *UserCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_UserCredentials proto.InternalMessageInfo

func (m *UserCredentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserCredentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Role                 string   `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60b917c2932c744, []int{3}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthResponse) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type PaymentRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RespAccNo            string   `protobuf:"bytes,2,opt,name=respAccNo,proto3" json:"respAccNo,omitempty"`
	Amount               float32  `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentRequest) Reset()         { *m = PaymentRequest{} }
func (m *PaymentRequest) String() string { return proto.CompactTextString(m) }
func (*PaymentRequest) ProtoMessage()    {}
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60b917c2932c744, []int{4}
}

func (m *PaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentRequest.Unmarshal(m, b)
}
func (m *PaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentRequest.Marshal(b, m, deterministic)
}
func (m *PaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentRequest.Merge(m, src)
}
func (m *PaymentRequest) XXX_Size() int {
	return xxx_messageInfo_PaymentRequest.Size(m)
}
func (m *PaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentRequest proto.InternalMessageInfo

func (m *PaymentRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *PaymentRequest) GetRespAccNo() string {
	if m != nil {
		return m.RespAccNo
	}
	return ""
}

func (m *PaymentRequest) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type PaymentResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentResponse) Reset()         { *m = PaymentResponse{} }
func (m *PaymentResponse) String() string { return proto.CompactTextString(m) }
func (*PaymentResponse) ProtoMessage()    {}
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60b917c2932c744, []int{5}
}

func (m *PaymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentResponse.Unmarshal(m, b)
}
func (m *PaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentResponse.Marshal(b, m, deterministic)
}
func (m *PaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentResponse.Merge(m, src)
}
func (m *PaymentResponse) XXX_Size() int {
	return xxx_messageInfo_PaymentResponse.Size(m)
}
func (m *PaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentResponse proto.InternalMessageInfo

func (m *PaymentResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PaymentResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DebitRequest struct {
	AccNo                string   `protobuf:"bytes,1,opt,name=AccNo,proto3" json:"AccNo,omitempty"`
	Amount               float32  `protobuf:"fixed32,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DebitRequest) Reset()         { *m = DebitRequest{} }
func (m *DebitRequest) String() string { return proto.CompactTextString(m) }
func (*DebitRequest) ProtoMessage()    {}
func (*DebitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60b917c2932c744, []int{6}
}

func (m *DebitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebitRequest.Unmarshal(m, b)
}
func (m *DebitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebitRequest.Marshal(b, m, deterministic)
}
func (m *DebitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebitRequest.Merge(m, src)
}
func (m *DebitRequest) XXX_Size() int {
	return xxx_messageInfo_DebitRequest.Size(m)
}
func (m *DebitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DebitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DebitRequest proto.InternalMessageInfo

func (m *DebitRequest) GetAccNo() string {
	if m != nil {
		return m.AccNo
	}
	return ""
}

func (m *DebitRequest) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type DebitResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DebitResponse) Reset()         { *m = DebitResponse{} }
func (m *DebitResponse) String() string { return proto.CompactTextString(m) }
func (*DebitResponse) ProtoMessage()    {}
func (*DebitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60b917c2932c744, []int{7}
}

func (m *DebitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebitResponse.Unmarshal(m, b)
}
func (m *DebitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebitResponse.Marshal(b, m, deterministic)
}
func (m *DebitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebitResponse.Merge(m, src)
}
func (m *DebitResponse) XXX_Size() int {
	return xxx_messageInfo_DebitResponse.Size(m)
}
func (m *DebitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DebitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DebitResponse proto.InternalMessageInfo

type CreditRequest struct {
	AccNo                string   `protobuf:"bytes,1,opt,name=AccNo,proto3" json:"AccNo,omitempty"`
	Amount               float32  `protobuf:"fixed32,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreditRequest) Reset()         { *m = CreditRequest{} }
func (m *CreditRequest) String() string { return proto.CompactTextString(m) }
func (*CreditRequest) ProtoMessage()    {}
func (*CreditRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60b917c2932c744, []int{8}
}

func (m *CreditRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreditRequest.Unmarshal(m, b)
}
func (m *CreditRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreditRequest.Marshal(b, m, deterministic)
}
func (m *CreditRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreditRequest.Merge(m, src)
}
func (m *CreditRequest) XXX_Size() int {
	return xxx_messageInfo_CreditRequest.Size(m)
}
func (m *CreditRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreditRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreditRequest proto.InternalMessageInfo

func (m *CreditRequest) GetAccNo() string {
	if m != nil {
		return m.AccNo
	}
	return ""
}

func (m *CreditRequest) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type CreditResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreditResponse) Reset()         { *m = CreditResponse{} }
func (m *CreditResponse) String() string { return proto.CompactTextString(m) }
func (*CreditResponse) ProtoMessage()    {}
func (*CreditResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60b917c2932c744, []int{9}
}

func (m *CreditResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreditResponse.Unmarshal(m, b)
}
func (m *CreditResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreditResponse.Marshal(b, m, deterministic)
}
func (m *CreditResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreditResponse.Merge(m, src)
}
func (m *CreditResponse) XXX_Size() int {
	return xxx_messageInfo_CreditResponse.Size(m)
}
func (m *CreditResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreditResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreditResponse proto.InternalMessageInfo

type CheckBalanceRequest struct {
	AccNo                string   `protobuf:"bytes,1,opt,name=AccNo,proto3" json:"AccNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckBalanceRequest) Reset()         { *m = CheckBalanceRequest{} }
func (m *CheckBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*CheckBalanceRequest) ProtoMessage()    {}
func (*CheckBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60b917c2932c744, []int{10}
}

func (m *CheckBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckBalanceRequest.Unmarshal(m, b)
}
func (m *CheckBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckBalanceRequest.Marshal(b, m, deterministic)
}
func (m *CheckBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckBalanceRequest.Merge(m, src)
}
func (m *CheckBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_CheckBalanceRequest.Size(m)
}
func (m *CheckBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckBalanceRequest proto.InternalMessageInfo

func (m *CheckBalanceRequest) GetAccNo() string {
	if m != nil {
		return m.AccNo
	}
	return ""
}

type CheckBalanceResponse struct {
	CurrBalance          float32  `protobuf:"fixed32,1,opt,name=CurrBalance,proto3" json:"CurrBalance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckBalanceResponse) Reset()         { *m = CheckBalanceResponse{} }
func (m *CheckBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*CheckBalanceResponse) ProtoMessage()    {}
func (*CheckBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c60b917c2932c744, []int{11}
}

func (m *CheckBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckBalanceResponse.Unmarshal(m, b)
}
func (m *CheckBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckBalanceResponse.Marshal(b, m, deterministic)
}
func (m *CheckBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckBalanceResponse.Merge(m, src)
}
func (m *CheckBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_CheckBalanceResponse.Size(m)
}
func (m *CheckBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckBalanceResponse proto.InternalMessageInfo

func (m *CheckBalanceResponse) GetCurrBalance() float32 {
	if m != nil {
		return m.CurrBalance
	}
	return 0
}

func init() {
	proto.RegisterType((*GetBalanceRequest)(nil), "paymentpb.GetBalanceRequest")
	proto.RegisterType((*GetBalanceResponse)(nil), "paymentpb.GetBalanceResponse")
	proto.RegisterType((*UserCredentials)(nil), "paymentpb.UserCredentials")
	proto.RegisterType((*AuthResponse)(nil), "paymentpb.AuthResponse")
	proto.RegisterType((*PaymentRequest)(nil), "paymentpb.PaymentRequest")
	proto.RegisterType((*PaymentResponse)(nil), "paymentpb.PaymentResponse")
	proto.RegisterType((*DebitRequest)(nil), "paymentpb.DebitRequest")
	proto.RegisterType((*DebitResponse)(nil), "paymentpb.DebitResponse")
	proto.RegisterType((*CreditRequest)(nil), "paymentpb.CreditRequest")
	proto.RegisterType((*CreditResponse)(nil), "paymentpb.CreditResponse")
	proto.RegisterType((*CheckBalanceRequest)(nil), "paymentpb.CheckBalanceRequest")
	proto.RegisterType((*CheckBalanceResponse)(nil), "paymentpb.CheckBalanceResponse")
}

func init() {
	proto.RegisterFile("protofiles/payment_gateway.proto", fileDescriptor_c60b917c2932c744)
}

var fileDescriptor_c60b917c2932c744 = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0x55, 0x02, 0x14, 0x32, 0x49, 0x1a, 0x30, 0x15, 0xa4, 0x56, 0x81, 0xc8, 0x27, 0x10, 0x28,
	0x95, 0xda, 0x4b, 0x0f, 0x70, 0x48, 0xb6, 0x12, 0xea, 0x81, 0x0f, 0x05, 0x71, 0x41, 0x48, 0xc8,
	0xd9, 0x0e, 0x6d, 0x94, 0xac, 0xbd, 0xb5, 0xbd, 0x54, 0xfd, 0xc3, 0xf0, 0x37, 0x50, 0xd6, 0xb3,
	0xbb, 0x5e, 0x36, 0xe1, 0xd0, 0x9b, 0x67, 0xde, 0xf3, 0xdb, 0x37, 0x9e, 0xa7, 0x85, 0x51, 0x6a,
	0xb4, 0xd3, 0x3f, 0x17, 0x2b, 0xb4, 0x87, 0xa9, 0xbc, 0x49, 0x50, 0xb9, 0x1f, 0x17, 0xd2, 0xe1,
	0xb5, 0xbc, 0x19, 0xe7, 0x10, 0xeb, 0x50, 0x3b, 0x9d, 0x8b, 0x57, 0xf0, 0xe8, 0x3d, 0xba, 0xa9,
	0x5c, 0x49, 0x15, 0xe3, 0x0c, 0xaf, 0x32, 0xb4, 0x8e, 0xed, 0xc1, 0x3d, 0xa7, 0x97, 0xa8, 0x86,
	0xad, 0x51, 0xeb, 0x65, 0x67, 0xe6, 0x0b, 0xf1, 0x06, 0x58, 0x48, 0xb5, 0xa9, 0x56, 0x16, 0xd9,
	0x13, 0xd8, 0x91, 0x89, 0xce, 0x94, 0xcb, 0xc9, 0xed, 0x19, 0x55, 0xe2, 0x0c, 0x06, 0x5f, 0x2d,
	0x9a, 0xc8, 0xe0, 0x39, 0x2a, 0xb7, 0x90, 0x2b, 0xcb, 0x38, 0x3c, 0xc8, 0x2c, 0x1a, 0x25, 0x13,
	0x24, 0xe5, 0xb2, 0x5e, 0x63, 0xa9, 0xb4, 0xf6, 0x5a, 0x9b, 0xf3, 0x61, 0xdb, 0x63, 0x45, 0x2d,
	0x4e, 0xa0, 0x37, 0xc9, 0xdc, 0x65, 0xf9, 0xc9, 0x8d, 0xf6, 0x18, 0x83, 0xbb, 0x46, 0xaf, 0x90,
	0x6e, 0xe7, 0x67, 0xf1, 0x1d, 0x76, 0x3f, 0xfb, 0x51, 0xff, 0x3b, 0x1a, 0x3b, 0x80, 0x8e, 0x41,
	0x9b, 0x4e, 0xe2, 0xf8, 0xa3, 0x26, 0x81, 0xaa, 0x11, 0x8c, 0x78, 0xa7, 0x36, 0x62, 0x04, 0x83,
	0x52, 0xbd, 0x7a, 0x0d, 0xeb, 0xa4, 0xcb, 0x2c, 0xe9, 0x53, 0xc5, 0x86, 0x70, 0x3f, 0x41, 0x6b,
	0xe5, 0x45, 0xe1, 0xaf, 0x28, 0xc5, 0x5b, 0xe8, 0x9d, 0xe2, 0x7c, 0x11, 0x1a, 0xf4, 0x36, 0xc8,
	0x60, 0x69, 0x61, 0xe2, 0x2d, 0xb4, 0xbd, 0x05, 0x5f, 0x89, 0x01, 0xf4, 0xe9, 0xb6, 0x37, 0x20,
	0xde, 0x41, 0x7f, 0xfd, 0xe4, 0xb7, 0xd5, 0x7b, 0x08, 0xbb, 0xc5, 0x75, 0x12, 0x7c, 0x0d, 0x8f,
	0xa3, 0x4b, 0x8c, 0x97, 0xcd, 0x88, 0x34, 0x65, 0xc5, 0x09, 0xec, 0xd5, 0xc9, 0xf4, 0x2c, 0x23,
	0xe8, 0x46, 0x99, 0x31, 0xd4, 0xa6, 0xa4, 0x84, 0xad, 0xa3, 0xdf, 0xad, 0x72, 0x55, 0x5f, 0xd0,
	0xfc, 0x5a, 0xc4, 0xc8, 0x22, 0xbf, 0xf6, 0x75, 0x7a, 0x62, 0xe9, 0x90, 0xf1, 0x71, 0x19, 0xdb,
	0xf1, 0x3f, 0xd1, 0xe2, 0x4f, 0x03, 0xac, 0x96, 0x95, 0x33, 0x80, 0x2a, 0xb4, 0xec, 0x20, 0xa0,
	0x35, 0x62, 0xcf, 0x9f, 0x6d, 0x41, 0x49, 0xea, 0x14, 0xba, 0x1f, 0xe4, 0x12, 0xc9, 0x25, 0xdb,
	0x0f, 0xd8, 0xf5, 0x90, 0x71, 0xbe, 0x09, 0xf2, 0x2a, 0x47, 0x7f, 0x5a, 0xd0, 0x9d, 0x4a, 0xb5,
	0x2c, 0xa6, 0x9c, 0xd0, 0xfe, 0x0b, 0x8b, 0xe1, 0x24, 0x61, 0x30, 0xf8, 0xb0, 0x09, 0x94, 0xc6,
	0x68, 0xe7, 0x85, 0x46, 0x48, 0xad, 0xa5, 0x81, 0xef, 0x6f, 0x40, 0x48, 0xe5, 0x13, 0xf4, 0xc2,
	0xdd, 0xb1, 0xe7, 0x21, 0xb5, 0x99, 0x00, 0xfe, 0x62, 0x2b, 0xee, 0x05, 0xa7, 0x83, 0x6f, 0xfd,
	0xab, 0xe3, 0xc3, 0xea, 0x67, 0x34, 0xdf, 0xc9, 0xcf, 0xc7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x49, 0xf2, 0xd8, 0xc2, 0xa1, 0x04, 0x00, 0x00,
}
