// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protofiles/message.proto

package protofiles

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BackendRequest struct {
	Load                 int64    `protobuf:"varint,1,opt,name=load,proto3" json:"load,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackendRequest) Reset()         { *m = BackendRequest{} }
func (m *BackendRequest) String() string { return proto.CompactTextString(m) }
func (*BackendRequest) ProtoMessage()    {}
func (*BackendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c0bf3230c4676e8, []int{0}
}

func (m *BackendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackendRequest.Unmarshal(m, b)
}
func (m *BackendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackendRequest.Marshal(b, m, deterministic)
}
func (m *BackendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackendRequest.Merge(m, src)
}
func (m *BackendRequest) XXX_Size() int {
	return xxx_messageInfo_BackendRequest.Size(m)
}
func (m *BackendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BackendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BackendRequest proto.InternalMessageInfo

func (m *BackendRequest) GetLoad() int64 {
	if m != nil {
		return m.Load
	}
	return 0
}

type BackendResponse struct {
	Feedback             string   `protobuf:"bytes,1,opt,name=feedback,proto3" json:"feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackendResponse) Reset()         { *m = BackendResponse{} }
func (m *BackendResponse) String() string { return proto.CompactTextString(m) }
func (*BackendResponse) ProtoMessage()    {}
func (*BackendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c0bf3230c4676e8, []int{1}
}

func (m *BackendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackendResponse.Unmarshal(m, b)
}
func (m *BackendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackendResponse.Marshal(b, m, deterministic)
}
func (m *BackendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackendResponse.Merge(m, src)
}
func (m *BackendResponse) XXX_Size() int {
	return xxx_messageInfo_BackendResponse.Size(m)
}
func (m *BackendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BackendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BackendResponse proto.InternalMessageInfo

func (m *BackendResponse) GetFeedback() string {
	if m != nil {
		return m.Feedback
	}
	return ""
}

type LoadBalancerRequest struct {
	Load                 int64    `protobuf:"varint,1,opt,name=load,proto3" json:"load,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadBalancerRequest) Reset()         { *m = LoadBalancerRequest{} }
func (m *LoadBalancerRequest) String() string { return proto.CompactTextString(m) }
func (*LoadBalancerRequest) ProtoMessage()    {}
func (*LoadBalancerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c0bf3230c4676e8, []int{2}
}

func (m *LoadBalancerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadBalancerRequest.Unmarshal(m, b)
}
func (m *LoadBalancerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadBalancerRequest.Marshal(b, m, deterministic)
}
func (m *LoadBalancerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadBalancerRequest.Merge(m, src)
}
func (m *LoadBalancerRequest) XXX_Size() int {
	return xxx_messageInfo_LoadBalancerRequest.Size(m)
}
func (m *LoadBalancerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadBalancerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadBalancerRequest proto.InternalMessageInfo

func (m *LoadBalancerRequest) GetLoad() int64 {
	if m != nil {
		return m.Load
	}
	return 0
}

type LoadBalancerResponse struct {
	BestServer           string   `protobuf:"bytes,1,opt,name=bestServer,proto3" json:"bestServer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadBalancerResponse) Reset()         { *m = LoadBalancerResponse{} }
func (m *LoadBalancerResponse) String() string { return proto.CompactTextString(m) }
func (*LoadBalancerResponse) ProtoMessage()    {}
func (*LoadBalancerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c0bf3230c4676e8, []int{3}
}

func (m *LoadBalancerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadBalancerResponse.Unmarshal(m, b)
}
func (m *LoadBalancerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadBalancerResponse.Marshal(b, m, deterministic)
}
func (m *LoadBalancerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadBalancerResponse.Merge(m, src)
}
func (m *LoadBalancerResponse) XXX_Size() int {
	return xxx_messageInfo_LoadBalancerResponse.Size(m)
}
func (m *LoadBalancerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadBalancerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadBalancerResponse proto.InternalMessageInfo

func (m *LoadBalancerResponse) GetBestServer() string {
	if m != nil {
		return m.BestServer
	}
	return ""
}

func init() {
	proto.RegisterType((*BackendRequest)(nil), "message.BackendRequest")
	proto.RegisterType((*BackendResponse)(nil), "message.BackendResponse")
	proto.RegisterType((*LoadBalancerRequest)(nil), "message.LoadBalancerRequest")
	proto.RegisterType((*LoadBalancerResponse)(nil), "message.LoadBalancerResponse")
}

func init() {
	proto.RegisterFile("protofiles/message.proto", fileDescriptor_5c0bf3230c4676e8)
}

var fileDescriptor_5c0bf3230c4676e8 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0xcd, 0x4b, 0x87, 0x40,
	0x10, 0x45, 0x8a, 0x3e, 0x06, 0x4a, 0xd8, 0x82, 0x44, 0x2a, 0x42, 0x3a, 0xd4, 0x21, 0x25, 0x83,
	0xae, 0x81, 0x5e, 0x23, 0xcc, 0x6e, 0xdd, 0xd6, 0xdd, 0x51, 0x44, 0xdb, 0xd5, 0x5d, 0xeb, 0xef,
	0x8f, 0x56, 0xdd, 0x94, 0xfa, 0xfd, 0x6e, 0x33, 0x6f, 0x1e, 0xef, 0x83, 0x01, 0xaf, 0x53, 0x72,
	0x90, 0x65, 0xdd, 0xa2, 0x8e, 0x3e, 0x50, 0x6b, 0x5a, 0x61, 0x68, 0x20, 0xb2, 0x3f, 0xad, 0xc1,
	0x35, 0x1c, 0x27, 0x94, 0x35, 0x28, 0x78, 0x8e, 0xfd, 0x27, 0xea, 0x81, 0x10, 0xd8, 0x6d, 0x25,
	0xe5, 0x9e, 0x73, 0xe5, 0xdc, 0xec, 0xe4, 0x66, 0x0e, 0xee, 0xc0, 0xb5, 0x2c, 0xdd, 0x49, 0xa1,
	0x91, 0xf8, 0x70, 0x50, 0x22, 0xf2, 0x82, 0xb2, 0xc6, 0x50, 0x0f, 0x73, 0xbb, 0x07, 0xb7, 0x70,
	0xf2, 0x2c, 0x29, 0x4f, 0x68, 0x4b, 0x05, 0x43, 0xb5, 0x4d, 0xf9, 0x11, 0x4e, 0xd7, 0xd4, 0x49,
	0xfe, 0x12, 0xa0, 0x40, 0x3d, 0xbc, 0xa1, 0xfa, 0x42, 0x35, 0x19, 0x2c, 0x90, 0xf8, 0xd5, 0xe6,
	0xfe, 0x01, 0x6a, 0x86, 0xe4, 0x09, 0x60, 0xce, 0x98, 0xa5, 0xe4, 0x2c, 0x9c, 0x0b, 0xaf, 0xeb,
	0xf9, 0xde, 0xdf, 0xc3, 0x68, 0x19, 0x97, 0xcb, 0x28, 0xb5, 0xa8, 0x66, 0xe1, 0x17, 0x70, 0x57,
	0x11, 0xb3, 0x94, 0x9c, 0x5b, 0x91, 0x7f, 0x7a, 0xfa, 0x17, 0x1b, 0xae, 0xa3, 0x4f, 0xe2, 0xbe,
	0x1f, 0xf5, 0xf7, 0xd1, 0xef, 0x6b, 0x8a, 0x3d, 0x33, 0x3f, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff,
	0xb7, 0xea, 0x94, 0x09, 0xaf, 0x01, 0x00, 0x00,
}
