// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protofiles/message.proto

package protofiles

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoadStatus struct {
	ServerAddr           string   `protobuf:"bytes,1,opt,name=serverAddr,proto3" json:"serverAddr,omitempty"`
	Load                 float32  `protobuf:"fixed32,2,opt,name=load,proto3" json:"load,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadStatus) Reset()         { *m = LoadStatus{} }
func (m *LoadStatus) String() string { return proto.CompactTextString(m) }
func (*LoadStatus) ProtoMessage()    {}
func (*LoadStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c0bf3230c4676e8, []int{0}
}

func (m *LoadStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadStatus.Unmarshal(m, b)
}
func (m *LoadStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadStatus.Marshal(b, m, deterministic)
}
func (m *LoadStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadStatus.Merge(m, src)
}
func (m *LoadStatus) XXX_Size() int {
	return xxx_messageInfo_LoadStatus.Size(m)
}
func (m *LoadStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadStatus.DiscardUnknown(m)
}

var xxx_messageInfo_LoadStatus proto.InternalMessageInfo

func (m *LoadStatus) GetServerAddr() string {
	if m != nil {
		return m.ServerAddr
	}
	return ""
}

func (m *LoadStatus) GetLoad() float32 {
	if m != nil {
		return m.Load
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c0bf3230c4676e8, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type BackendRequest struct {
	TaskType             int32    `protobuf:"varint,1,opt,name=taskType,proto3" json:"taskType,omitempty"`
	Num                  int64    `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackendRequest) Reset()         { *m = BackendRequest{} }
func (m *BackendRequest) String() string { return proto.CompactTextString(m) }
func (*BackendRequest) ProtoMessage()    {}
func (*BackendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c0bf3230c4676e8, []int{2}
}

func (m *BackendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackendRequest.Unmarshal(m, b)
}
func (m *BackendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackendRequest.Marshal(b, m, deterministic)
}
func (m *BackendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackendRequest.Merge(m, src)
}
func (m *BackendRequest) XXX_Size() int {
	return xxx_messageInfo_BackendRequest.Size(m)
}
func (m *BackendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BackendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BackendRequest proto.InternalMessageInfo

func (m *BackendRequest) GetTaskType() int32 {
	if m != nil {
		return m.TaskType
	}
	return 0
}

func (m *BackendRequest) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type BackendResponse struct {
	Output               int64    `protobuf:"varint,1,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackendResponse) Reset()         { *m = BackendResponse{} }
func (m *BackendResponse) String() string { return proto.CompactTextString(m) }
func (*BackendResponse) ProtoMessage()    {}
func (*BackendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c0bf3230c4676e8, []int{3}
}

func (m *BackendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackendResponse.Unmarshal(m, b)
}
func (m *BackendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackendResponse.Marshal(b, m, deterministic)
}
func (m *BackendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackendResponse.Merge(m, src)
}
func (m *BackendResponse) XXX_Size() int {
	return xxx_messageInfo_BackendResponse.Size(m)
}
func (m *BackendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BackendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BackendResponse proto.InternalMessageInfo

func (m *BackendResponse) GetOutput() int64 {
	if m != nil {
		return m.Output
	}
	return 0
}

type LoadBalancerRequest struct {
	TaskType             int32    `protobuf:"varint,1,opt,name=taskType,proto3" json:"taskType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadBalancerRequest) Reset()         { *m = LoadBalancerRequest{} }
func (m *LoadBalancerRequest) String() string { return proto.CompactTextString(m) }
func (*LoadBalancerRequest) ProtoMessage()    {}
func (*LoadBalancerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c0bf3230c4676e8, []int{4}
}

func (m *LoadBalancerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadBalancerRequest.Unmarshal(m, b)
}
func (m *LoadBalancerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadBalancerRequest.Marshal(b, m, deterministic)
}
func (m *LoadBalancerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadBalancerRequest.Merge(m, src)
}
func (m *LoadBalancerRequest) XXX_Size() int {
	return xxx_messageInfo_LoadBalancerRequest.Size(m)
}
func (m *LoadBalancerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadBalancerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadBalancerRequest proto.InternalMessageInfo

func (m *LoadBalancerRequest) GetTaskType() int32 {
	if m != nil {
		return m.TaskType
	}
	return 0
}

type LoadBalancerResponse struct {
	BestServer           string   `protobuf:"bytes,1,opt,name=bestServer,proto3" json:"bestServer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadBalancerResponse) Reset()         { *m = LoadBalancerResponse{} }
func (m *LoadBalancerResponse) String() string { return proto.CompactTextString(m) }
func (*LoadBalancerResponse) ProtoMessage()    {}
func (*LoadBalancerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c0bf3230c4676e8, []int{5}
}

func (m *LoadBalancerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadBalancerResponse.Unmarshal(m, b)
}
func (m *LoadBalancerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadBalancerResponse.Marshal(b, m, deterministic)
}
func (m *LoadBalancerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadBalancerResponse.Merge(m, src)
}
func (m *LoadBalancerResponse) XXX_Size() int {
	return xxx_messageInfo_LoadBalancerResponse.Size(m)
}
func (m *LoadBalancerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadBalancerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadBalancerResponse proto.InternalMessageInfo

func (m *LoadBalancerResponse) GetBestServer() string {
	if m != nil {
		return m.BestServer
	}
	return ""
}

func init() {
	proto.RegisterType((*LoadStatus)(nil), "message.LoadStatus")
	proto.RegisterType((*Empty)(nil), "message.Empty")
	proto.RegisterType((*BackendRequest)(nil), "message.BackendRequest")
	proto.RegisterType((*BackendResponse)(nil), "message.BackendResponse")
	proto.RegisterType((*LoadBalancerRequest)(nil), "message.LoadBalancerRequest")
	proto.RegisterType((*LoadBalancerResponse)(nil), "message.LoadBalancerResponse")
}

func init() {
	proto.RegisterFile("protofiles/message.proto", fileDescriptor_5c0bf3230c4676e8)
}

var fileDescriptor_5c0bf3230c4676e8 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcb, 0x4f, 0x32, 0x31,
	0x10, 0x0f, 0xf0, 0x01, 0x9f, 0x93, 0x00, 0x5a, 0x8c, 0x6e, 0x36, 0x4a, 0x48, 0x4f, 0x78, 0x81,
	0x80, 0xc6, 0xa3, 0x0f, 0x88, 0x07, 0x13, 0x63, 0xb0, 0x78, 0xf2, 0x56, 0xd8, 0x81, 0x10, 0x76,
	0xb7, 0xa5, 0xed, 0x9a, 0xf0, 0xdf, 0x9b, 0x2d, 0xfb, 0x60, 0xa3, 0x26, 0xde, 0x66, 0x7e, 0xcd,
	0xfc, 0x1e, 0x9d, 0x01, 0x47, 0x2a, 0x61, 0xc4, 0x72, 0xed, 0xa3, 0x1e, 0x04, 0xa8, 0x35, 0x5f,
	0x61, 0xdf, 0x42, 0xa4, 0x9e, 0xb4, 0xf4, 0x01, 0xe0, 0x45, 0x70, 0x6f, 0x66, 0xb8, 0x89, 0x34,
	0xe9, 0x00, 0x68, 0x54, 0x9f, 0xa8, 0x1e, 0x3d, 0x4f, 0x39, 0xa5, 0x6e, 0xa9, 0x77, 0xc4, 0x0e,
	0x10, 0x42, 0xe0, 0x9f, 0x2f, 0xb8, 0xe7, 0x94, 0xbb, 0xa5, 0x5e, 0x99, 0xd9, 0x9a, 0xd6, 0xa1,
	0xfa, 0x14, 0x48, 0xb3, 0xa3, 0x77, 0xd0, 0x1c, 0xf3, 0xc5, 0x06, 0x43, 0x8f, 0xe1, 0x36, 0x42,
	0x6d, 0x88, 0x0b, 0xff, 0x0d, 0xd7, 0x9b, 0xf7, 0x9d, 0x44, 0x4b, 0x56, 0x65, 0x59, 0x4f, 0x8e,
	0xa1, 0x12, 0x46, 0x81, 0x65, 0xaa, 0xb0, 0xb8, 0xa4, 0x57, 0xd0, 0xca, 0xe6, 0xb5, 0x14, 0xa1,
	0x46, 0x72, 0x06, 0x35, 0x11, 0x19, 0x19, 0x19, 0x3b, 0x5e, 0x61, 0x49, 0x47, 0x87, 0xd0, 0x8e,
	0x5d, 0x8f, 0xb9, 0xcf, 0xc3, 0x05, 0xaa, 0x3f, 0xe8, 0xd1, 0x5b, 0x38, 0x2d, 0x8e, 0x24, 0x12,
	0x1d, 0x80, 0x39, 0x6a, 0x33, 0xb3, 0x21, 0xd3, 0xc8, 0x39, 0x32, 0x7a, 0xcb, 0x52, 0xc5, 0xc0,
	0x7a, 0x81, 0xe4, 0x1e, 0x20, 0xf5, 0x39, 0x9d, 0x90, 0xf3, 0x7e, 0xfa, 0xb3, 0xc5, 0xf0, 0xae,
	0xf3, 0xfd, 0x61, 0x2f, 0x39, 0x5a, 0x1e, 0x5a, 0x59, 0x87, 0xab, 0x94, 0xf8, 0x15, 0x5a, 0x05,
	0x8b, 0xd3, 0x09, 0xb9, 0xc8, 0x48, 0x7e, 0xc8, 0xeb, 0x5e, 0xfe, 0xf2, 0x9a, 0xe8, 0x3c, 0xc3,
	0x09, 0x43, 0x29, 0x94, 0xb1, 0x1b, 0x4e, 0x44, 0x6e, 0xa0, 0x91, 0x83, 0xb1, 0x44, 0xbb, 0x40,
	0xb2, 0x3f, 0x04, 0xb7, 0x99, 0x81, 0x76, 0xb7, 0xe3, 0xd6, 0x47, 0x63, 0x3b, 0x1c, 0xe4, 0xe7,
	0x34, 0xaf, 0xd9, 0xfa, 0xfa, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x72, 0x00, 0xf9, 0xba, 0x63, 0x02,
	0x00, 0x00,
}
