// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protofiles/mapreduce.proto

package protofiles

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_e758f9057fa6d460, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type MapResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapResult) Reset()         { *m = MapResult{} }
func (m *MapResult) String() string { return proto.CompactTextString(m) }
func (*MapResult) ProtoMessage()    {}
func (*MapResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e758f9057fa6d460, []int{1}
}

func (m *MapResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapResult.Unmarshal(m, b)
}
func (m *MapResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapResult.Marshal(b, m, deterministic)
}
func (m *MapResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapResult.Merge(m, src)
}
func (m *MapResult) XXX_Size() int {
	return xxx_messageInfo_MapResult.Size(m)
}
func (m *MapResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MapResult.DiscardUnknown(m)
}

var xxx_messageInfo_MapResult proto.InternalMessageInfo

type ReduceResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReduceResult) Reset()         { *m = ReduceResult{} }
func (m *ReduceResult) String() string { return proto.CompactTextString(m) }
func (*ReduceResult) ProtoMessage()    {}
func (*ReduceResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e758f9057fa6d460, []int{2}
}

func (m *ReduceResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReduceResult.Unmarshal(m, b)
}
func (m *ReduceResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReduceResult.Marshal(b, m, deterministic)
}
func (m *ReduceResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReduceResult.Merge(m, src)
}
func (m *ReduceResult) XXX_Size() int {
	return xxx_messageInfo_ReduceResult.Size(m)
}
func (m *ReduceResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ReduceResult.DiscardUnknown(m)
}

var xxx_messageInfo_ReduceResult proto.InternalMessageInfo

type MapResultResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapResultResponse) Reset()         { *m = MapResultResponse{} }
func (m *MapResultResponse) String() string { return proto.CompactTextString(m) }
func (*MapResultResponse) ProtoMessage()    {}
func (*MapResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e758f9057fa6d460, []int{3}
}

func (m *MapResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapResultResponse.Unmarshal(m, b)
}
func (m *MapResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapResultResponse.Marshal(b, m, deterministic)
}
func (m *MapResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapResultResponse.Merge(m, src)
}
func (m *MapResultResponse) XXX_Size() int {
	return xxx_messageInfo_MapResultResponse.Size(m)
}
func (m *MapResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MapResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MapResultResponse proto.InternalMessageInfo

type ReduceResultResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReduceResultResponse) Reset()         { *m = ReduceResultResponse{} }
func (m *ReduceResultResponse) String() string { return proto.CompactTextString(m) }
func (*ReduceResultResponse) ProtoMessage()    {}
func (*ReduceResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e758f9057fa6d460, []int{4}
}

func (m *ReduceResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReduceResultResponse.Unmarshal(m, b)
}
func (m *ReduceResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReduceResultResponse.Marshal(b, m, deterministic)
}
func (m *ReduceResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReduceResultResponse.Merge(m, src)
}
func (m *ReduceResultResponse) XXX_Size() int {
	return xxx_messageInfo_ReduceResultResponse.Size(m)
}
func (m *ReduceResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReduceResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReduceResultResponse proto.InternalMessageInfo

type MapRequest struct {
	Inputfile            string   `protobuf:"bytes,1,opt,name=inputfile,proto3" json:"inputfile,omitempty"`
	NumReduce            int32    `protobuf:"varint,2,opt,name=numReduce,proto3" json:"numReduce,omitempty"`
	MapperId             int32    `protobuf:"varint,3,opt,name=mapperId,proto3" json:"mapperId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapRequest) Reset()         { *m = MapRequest{} }
func (m *MapRequest) String() string { return proto.CompactTextString(m) }
func (*MapRequest) ProtoMessage()    {}
func (*MapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e758f9057fa6d460, []int{5}
}

func (m *MapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapRequest.Unmarshal(m, b)
}
func (m *MapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapRequest.Marshal(b, m, deterministic)
}
func (m *MapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapRequest.Merge(m, src)
}
func (m *MapRequest) XXX_Size() int {
	return xxx_messageInfo_MapRequest.Size(m)
}
func (m *MapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MapRequest proto.InternalMessageInfo

func (m *MapRequest) GetInputfile() string {
	if m != nil {
		return m.Inputfile
	}
	return ""
}

func (m *MapRequest) GetNumReduce() int32 {
	if m != nil {
		return m.NumReduce
	}
	return 0
}

func (m *MapRequest) GetMapperId() int32 {
	if m != nil {
		return m.MapperId
	}
	return 0
}

type ReduceRequest struct {
	ReducerId            int32    `protobuf:"varint,1,opt,name=reducerId,proto3" json:"reducerId,omitempty"`
	NumMappers           int32    `protobuf:"varint,2,opt,name=numMappers,proto3" json:"numMappers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReduceRequest) Reset()         { *m = ReduceRequest{} }
func (m *ReduceRequest) String() string { return proto.CompactTextString(m) }
func (*ReduceRequest) ProtoMessage()    {}
func (*ReduceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e758f9057fa6d460, []int{6}
}

func (m *ReduceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReduceRequest.Unmarshal(m, b)
}
func (m *ReduceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReduceRequest.Marshal(b, m, deterministic)
}
func (m *ReduceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReduceRequest.Merge(m, src)
}
func (m *ReduceRequest) XXX_Size() int {
	return xxx_messageInfo_ReduceRequest.Size(m)
}
func (m *ReduceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReduceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReduceRequest proto.InternalMessageInfo

func (m *ReduceRequest) GetReducerId() int32 {
	if m != nil {
		return m.ReducerId
	}
	return 0
}

func (m *ReduceRequest) GetNumMappers() int32 {
	if m != nil {
		return m.NumMappers
	}
	return 0
}

type MapResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapResponse) Reset()         { *m = MapResponse{} }
func (m *MapResponse) String() string { return proto.CompactTextString(m) }
func (*MapResponse) ProtoMessage()    {}
func (*MapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e758f9057fa6d460, []int{7}
}

func (m *MapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapResponse.Unmarshal(m, b)
}
func (m *MapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapResponse.Marshal(b, m, deterministic)
}
func (m *MapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapResponse.Merge(m, src)
}
func (m *MapResponse) XXX_Size() int {
	return xxx_messageInfo_MapResponse.Size(m)
}
func (m *MapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MapResponse proto.InternalMessageInfo

type ReduceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReduceResponse) Reset()         { *m = ReduceResponse{} }
func (m *ReduceResponse) String() string { return proto.CompactTextString(m) }
func (*ReduceResponse) ProtoMessage()    {}
func (*ReduceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e758f9057fa6d460, []int{8}
}

func (m *ReduceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReduceResponse.Unmarshal(m, b)
}
func (m *ReduceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReduceResponse.Marshal(b, m, deterministic)
}
func (m *ReduceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReduceResponse.Merge(m, src)
}
func (m *ReduceResponse) XXX_Size() int {
	return xxx_messageInfo_ReduceResponse.Size(m)
}
func (m *ReduceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReduceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReduceResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Empty)(nil), "mapreduce.Empty")
	proto.RegisterType((*MapResult)(nil), "mapreduce.MapResult")
	proto.RegisterType((*ReduceResult)(nil), "mapreduce.ReduceResult")
	proto.RegisterType((*MapResultResponse)(nil), "mapreduce.MapResultResponse")
	proto.RegisterType((*ReduceResultResponse)(nil), "mapreduce.ReduceResultResponse")
	proto.RegisterType((*MapRequest)(nil), "mapreduce.MapRequest")
	proto.RegisterType((*ReduceRequest)(nil), "mapreduce.ReduceRequest")
	proto.RegisterType((*MapResponse)(nil), "mapreduce.MapResponse")
	proto.RegisterType((*ReduceResponse)(nil), "mapreduce.ReduceResponse")
}

func init() {
	proto.RegisterFile("protofiles/mapreduce.proto", fileDescriptor_e758f9057fa6d460)
}

var fileDescriptor_e758f9057fa6d460 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x5f, 0x4f, 0xf2, 0x30,
	0x14, 0xc6, 0xb3, 0xf7, 0x0d, 0xe0, 0x0e, 0x0c, 0xb0, 0x20, 0xce, 0x85, 0x28, 0xd9, 0x15, 0x37,
	0x42, 0x82, 0x17, 0xde, 0x1a, 0x16, 0x2e, 0x8c, 0x21, 0x59, 0xc6, 0x85, 0x89, 0x77, 0xfc, 0xa9,
	0xc9, 0x22, 0xdb, 0xca, 0xda, 0x1a, 0xfd, 0x42, 0x7e, 0x07, 0xbf, 0x9d, 0x69, 0x3b, 0xda, 0x21,
	0x78, 0xb7, 0xfe, 0x9e, 0xd3, 0xe7, 0x9c, 0x67, 0xa7, 0xe0, 0x91, 0x3c, 0x63, 0xd9, 0x6b, 0xbc,
	0xc5, 0x74, 0x9c, 0x2c, 0x49, 0x8e, 0x37, 0x7c, 0x8d, 0x47, 0x12, 0x22, 0x5b, 0x03, 0xbf, 0x06,
	0x95, 0x59, 0x42, 0xd8, 0xa7, 0x5f, 0x07, 0x7b, 0xbe, 0x24, 0x11, 0xa6, 0x7c, 0xcb, 0xfc, 0x26,
	0x34, 0x22, 0xa9, 0x17, 0xe7, 0x0e, 0x9c, 0x6b, 0x31, 0xc2, 0x94, 0x64, 0x29, 0xc5, 0x7e, 0x0f,
	0xba, 0xe5, 0x22, 0xcd, 0x37, 0x00, 0xb2, 0x78, 0xc7, 0x31, 0x65, 0xa8, 0x0f, 0x76, 0x9c, 0x12,
	0xce, 0xc4, 0x24, 0xae, 0x35, 0xb0, 0x86, 0x76, 0x64, 0x80, 0x50, 0x53, 0x9e, 0x28, 0x1b, 0xf7,
	0xdf, 0xc0, 0x1a, 0x56, 0x22, 0x03, 0x90, 0x07, 0x67, 0xc9, 0x92, 0x10, 0x9c, 0x3f, 0x6e, 0xdc,
	0xff, 0x52, 0xd4, 0x67, 0x7f, 0x0e, 0xce, 0xbe, 0xbb, 0x6e, 0xa4, 0x32, 0x89, 0x6a, 0x4b, 0x59,
	0x69, 0x80, 0xae, 0x01, 0x52, 0x9e, 0xcc, 0xe5, 0x6d, 0x5a, 0x74, 0x2a, 0x11, 0xdf, 0x81, 0xba,
	0x4a, 0xa8, 0x32, 0xb4, 0xa1, 0xa9, 0xb3, 0x49, 0x32, 0xf9, 0xb6, 0xc0, 0x79, 0xce, 0xf2, 0x37,
	0x9c, 0x2f, 0x70, 0xfe, 0x1e, 0xaf, 0x31, 0xba, 0x87, 0xaa, 0xb8, 0x12, 0x06, 0xe8, 0x62, 0x64,
	0xfe, 0xb0, 0x89, 0xee, 0xf5, 0x7e, 0x63, 0x65, 0x85, 0x1e, 0xc0, 0x2e, 0xcc, 0xc3, 0x00, 0xb9,
	0xa5, 0xa2, 0x83, 0x40, 0xde, 0xd5, 0x09, 0xa5, 0x70, 0xb8, 0x85, 0xda, 0xec, 0x23, 0x66, 0xe2,
	0x7e, 0xbb, 0x54, 0x25, 0x37, 0xe9, 0x1d, 0x91, 0xc9, 0x97, 0x05, 0x9d, 0x05, 0x5f, 0x25, 0x31,
	0x53, 0xab, 0xda, 0x27, 0x98, 0x42, 0xc3, 0xac, 0x35, 0x0c, 0x50, 0xf7, 0x68, 0x60, 0xbe, 0x65,
	0x5e, 0xff, 0x14, 0xd5, 0xa3, 0x3c, 0x41, 0xeb, 0xe0, 0x15, 0x84, 0x01, 0xba, 0x3c, 0x35, 0xb8,
	0x70, 0xba, 0xf9, 0x43, 0xd8, 0x9b, 0x4d, 0x5b, 0x2f, 0xce, 0x6e, 0x32, 0x36, 0x2f, 0x77, 0x55,
	0x95, 0xdf, 0x77, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x92, 0xaa, 0xd3, 0x0b, 0xce, 0x02, 0x00,
	0x00,
}
